version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    env_file: 
      - secrets.env
    volumes:
      - ./mongo/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db
    networks:
      - mongo-network

  tweet-daemon:
    image: tweet-daemon
    build: ./tweet_daemon
    env_file: 
      - secrets.env
    networks:
      - mongo-network
  fastapi-tweet-backend:
    image: fastapi-tweet-backend
    build:
       context: ./services/api
    command: gunicorn main:app --bind 0.0.0.0:5000 -w 4 -k uvicorn.workers.UvicornWorker
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`api.sdps.badsartor.com`)"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"
    env_file: 
      - secrets.env
    networks:
      - mongo-network

#  traefik:
#    image: traefik:v2.2
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock:ro"
#      - "$PWD/services/traefik/traefik.prod.toml:/etc/traefik/traefik.toml"

networks: 
  mongo-network:

volumes:
  mongo-data: