version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    env_file: 
      - secrets.env
    volumes:
      - ./mongo/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db
    networks:
      - mongo-network

  tweet-daemon:
    image: tweet-daemon
    build: ./tweet_daemon
    env_file: 
      - secrets.env
    networks:
      - mongo-network

  reddit-daemon:
    image: reddit-daemon
    build: ./reddit_daemon
    env_file: 
      - secrets.env
    networks:
      - mongo-network

  fastapi-tweet-backend:
    image: fastapi-tweet-backend
    build:
       context: ./fastapi_backend
    env_file:
      - secrets.env
    expose:
      - 5000
    networks:
      - mongo-network
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"

  traefik:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./services/traefik/traefik.dev.toml:/etc/traefik/traefik.toml"
    networks:
      - default

networks: 
  mongo-network:

volumes:
  mongo-data: